/* Quiet Operations reminder: metrics stay compact and evidence-led; status color is meaningful, and every action has a visible next step. */
import { ArrowUpRight, ChevronRight, CircleAlert, Clock3, Filter, MoreHorizontal, Package, Plus, TrendingUp, UsersRound } from "lucide-react";
import { useLocation } from "wouter";
import AppShell from "@/components/AppShell";
import { toast } from "sonner";

const stats = [
  { label: "Eligible today", value: "1,284", delta: "+8.4%", note: "vs. yesterday", icon: UsersRound, tone: "blue" },
  { label: "Active offers", value: "368", delta: "+22", note: "in operator queue", icon: TrendingUp, tone: "green" },
  { label: "Orders this week", value: "92", delta: "+14.1%", note: "confirmed + fulfilling", icon: Package, tone: "sand" },
  { label: "Attach revenue", value: "KES 184.6k", delta: "KES 12.8k", note: "gross profit this week", icon: ArrowUpRight, tone: "ink" },
];
const attention = [
  { title: "7 inventory rows rejected", detail: "Non-Tier 1 category · awaiting correction", action: "Review import", tone: "coral" },
  { title: "12 customers auto-suppressed", detail: "Missed payment or open complaint", action: "View safeguards", tone: "coral" },
  { title: "Rule has zero matches", detail: "High value · 7 days since last run", action: "Inspect rule", tone: "blue" },
];
const queue = [
  { name: "Wanjiku Njeri", location: "Nairobi · Dandora", product: "Soundcore Mini Buds", daily: "KES 11/day", headroom: "KES 14", score: "94", signal: "Ready" },
  { name: "Brian Otieno", location: "Kisumu · Kibuye", product: "10,000mAh Power Bank", daily: "KES 9/day", headroom: "KES 10", score: "88", signal: "Review" },
  { name: "Mariam Achieng", location: "Mombasa · Likoni", product: "Braided USB-C Cable", daily: "KES 5/day", headroom: "KES 18", score: "91", signal: "Ready" },
  { name: "Samuel Kiptoo", location: "Nakuru · CBD", product: "Slim Clear Case", daily: "KES 7/day", headroom: "KES 12", score: "86", signal: "Ready" },
];

function StatCard({ item }: { item: typeof stats[number] }) {
  const Icon = item.icon;
  return <div className="qo-hover-lift rounded-xl border border-[#e2e7ee] bg-white p-4"><div className="flex items-start justify-between"><span className={`flex h-8 w-8 items-center justify-center rounded-lg ${item.tone === 'blue' ? 'bg-[#fff0f1] text-[#e60012]' : item.tone === 'green' ? 'bg-[#fff0f1] text-[#6d6d6d]' : item.tone === 'sand' ? 'bg-[#fff5e8] text-[#bf7c39]' : 'bg-[#edf0f4] text-[#3b4858]'}`}><Icon size={16} strokeWidth={1.8} /></span><MoreHorizontal size={16} className="text-[#abb4be]" /></div><div className="mt-5 text-[25px] font-bold tracking-[-0.065em] text-[#202b37]">{item.value}</div><div className="mt-1 flex items-center gap-1.5 text-[11px] font-bold"><span className={item.tone === 'coral' ? 'text-[#bd6b60]' : 'text-[#6d6d6d]'}>{item.delta}</span><span className="font-medium text-[#98a3af]">{item.note}</span></div><div className="mt-4 h-1 overflow-hidden rounded-full bg-[#edf1f5]"><div className={`h-full rounded-full ${item.tone === 'blue' ? 'w-[72%] bg-[#e60012]' : item.tone === 'green' ? 'w-[84%] bg-[#6d6d6d]' : item.tone === 'sand' ? 'w-[58%] bg-[#6d6d6d]' : 'w-[67%] bg-[#657181]'}`} /></div></div>;
}

export default function CommandCenter() {
  const [, setLocation] = useLocation();
  return <AppShell eyebrow="Workspace / overview" title="Command center" action={<button type="button" onClick={() => toast.success("Automation preview queued for this demo.")} className="qo-button hidden items-center gap-2 rounded-lg bg-[#e60012] px-3.5 py-2.5 text-[11px] font-bold text-white shadow-[0_8px_18px_rgba(230,0,18,0.16)] hover:bg-[#b8000e] sm:flex"><Plus size={14} /> Run an automation</button>}>
    <div className="mx-auto max-w-[1320px]">
      <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[13px] text-[#748091]">Tuesday, 27 August 2026 <span className="mx-2 text-[#c2c9d1]">/</span> Shift 02</p><p className="mt-1 text-[11px] text-[#9aa5b2]">A calm view of what needs a decision next.</p></div><div className="flex items-center gap-2 text-[11px] font-semibold text-[#7d8997]"><span className="h-2 w-2 rounded-full bg-[#6d6d6d]" /> All systems simulated · last sync 12 min ago</div></div>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{stats.map((item) => <StatCard item={item} key={item.label} />)}</div>
      <div className="mt-7 grid gap-6 xl:grid-cols-[1.25fr_0.75fr]">
        <section className="rounded-xl border border-[#e2e7ee] bg-white p-5 sm:p-6"><div className="flex items-center justify-between"><div><div className="qo-eyebrow text-[#e60012]">Offer funnel</div><h2 className="mt-1 text-[16px] font-bold tracking-[-0.03em]">From recommendation to repayment</h2></div><button type="button" onClick={() => toast.info("Analytics is staged for the next prototype pass.")} className="flex items-center gap-1 text-[11px] font-bold text-[#e60012] hover:underline">View analytics <ArrowUpRight size={13} /></button></div><div className="mt-8 flex items-end justify-between gap-2 sm:gap-5">{[['Recommended','1,284','w-full'],['Sent','842','w-[83%]'],['Clicked','516','w-[63%]'],['Confirmed','214','w-[42%]'],['Fulfilled','162','w-[32%]'],['Repaying','138','w-[27%]']].map(([label,value,width],i) => <div className="flex flex-1 flex-col items-center gap-2" key={label}><div className="flex h-[150px] w-full items-end"><div className={`mx-auto ${i === 0 ? 'bg-[#f7d9dc]' : i < 3 ? 'bg-[#f7d9dc]' : i < 5 ? 'bg-[#e60012]' : 'bg-[#e60012]'} ${width} rounded-t-md transition-all`} style={{ height: `${[100,82,63,46,38,32][i]}%` }} /></div><div className="text-[14px] font-bold tracking-[-0.03em]">{value}</div><div className="text-center text-[9px] font-bold leading-tight text-[#8e9aa8]">{label}</div></div>)}</div><div className="mt-7 flex items-center gap-5 border-t border-[#edf0f4] pt-4 text-[10px] font-semibold text-[#8190a0]"><span className="flex items-center gap-1.5"><span className="h-2 w-2 rounded-full bg-[#f7d9dc]" /> Eligible</span><span className="flex items-center gap-1.5"><span className="h-2 w-2 rounded-full bg-[#e60012]" /> In motion</span><span className="flex items-center gap-1.5"><span className="h-2 w-2 rounded-full bg-[#e60012]" /> Customer value</span></div></section>
        <section className="rounded-xl border border-[#e2e7ee] bg-white p-5 sm:p-6"><div className="flex items-center justify-between"><div><div className="qo-eyebrow text-[#bd6b60]">Needs attention</div><h2 className="mt-1 text-[16px] font-bold tracking-[-0.03em]">Keep the station clean</h2></div><CircleAlert size={18} className="text-[#e47b71]" /></div><div className="mt-5 space-y-3">{attention.map((item) => <button key={item.title} type="button" onClick={() => toast.info(item.action + " is staged for this demo.")} className="group flex w-full items-start gap-3 rounded-lg border border-[#edf0f4] p-3 text-left transition-colors hover:border-[#efd0d3] hover:bg-[#fafcff]"><span className={`mt-0.5 h-2 w-2 shrink-0 rounded-full ${item.tone === 'coral' ? 'bg-[#e47b71]' : 'bg-[#e60012]'}`} /><span className="min-w-0 flex-1"><span className="block text-[11px] font-bold text-[#435166]">{item.title}</span><span className="mt-1 block text-[10px] leading-[1.45] text-[#8994a2]">{item.detail}</span></span><ChevronRight size={14} className="mt-1 text-[#b6bec8] transition-transform group-hover:translate-x-0.5" /></button>)}</div><button type="button" onClick={() => toast.success("Attention queue marked as reviewed for this demo.")} className="mt-5 w-full rounded-lg border border-[#dce3eb] py-2.5 text-[11px] font-bold text-[#607084] transition-colors hover:border-[#e9b0b5] hover:text-[#e60012]">Mark review complete</button></section>
      </div>
      <section className="mt-6 overflow-hidden rounded-xl border border-[#e2e7ee] bg-white"><div className="flex flex-col justify-between gap-4 border-b border-[#edf0f4] p-5 sm:flex-row sm:items-center sm:p-6"><div><div className="qo-eyebrow text-[#e60012]">Next best action</div><h2 className="mt-1 text-[16px] font-bold tracking-[-0.03em]">Customers ready for a considered offer</h2></div><div className="flex items-center gap-2"><button type="button" onClick={() => toast.info("Filter tray is staged for this demo.")} className="flex items-center gap-1.5 rounded-lg border border-[#dce3eb] px-3 py-2 text-[11px] font-bold text-[#607084] hover:border-[#e9b0b5] hover:text-[#e60012]"><Filter size={13} /> Filters</button><button type="button" onClick={() => setLocation('/catalogue')} className="flex items-center gap-1.5 rounded-lg bg-[#fff0f1] px-3 py-2 text-[11px] font-bold text-[#e60012] hover:bg-[#f7d9dc]">Browse catalogue <ArrowUpRight size={13} /></button></div></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead className="bg-[#fafbfd]"><tr className="text-[10px] font-bold uppercase tracking-[0.12em] text-[#9aa5b2]"><th className="px-6 py-3 font-bold">Customer</th><th className="px-4 py-3 font-bold">Product match</th><th className="px-4 py-3 font-bold">Daily / combined</th><th className="px-4 py-3 font-bold">Score</th><th className="px-4 py-3 font-bold">Signal</th><th className="px-6 py-3 text-right font-bold">Action</th></tr></thead><tbody>{queue.map((row) => <tr key={row.name} className="border-t border-[#edf0f4] text-[11px] hover:bg-[#fbfcfe]"><td className="px-6 py-4"><div className="font-bold text-[#3e4b5b]">{row.name}</div><div className="mt-1 text-[10px] text-[#98a3af]">{row.location}</div></td><td className="px-4 py-4 font-semibold text-[#546275]">{row.product}</td><td className="px-4 py-4"><div className="font-bold text-[#3e4b5b]">{row.daily}</div><div className="mt-1 text-[10px] text-[#98a3af]">{row.headroom} headroom</div></td><td className="px-4 py-4 font-bold text-[#3e4b5b]">{row.score}<span className="font-medium text-[#a4adb8]"> / 100</span></td><td className="px-4 py-4"><span className={`rounded-full px-2 py-1 text-[9px] font-bold ${row.signal === 'Ready' ? 'bg-[#fff0f1] text-[#6d6d6d]' : 'bg-[#fff4e7] text-[#6d6d6d]'}`}>{row.signal}</span></td><td className="px-6 py-4 text-right"><button type="button" onClick={() => toast.success(`Demo offer prepared for ${row.name}.`)} className="rounded-md px-2 py-1.5 text-[10px] font-bold text-[#e60012] hover:bg-[#fff0f1]">Review offer</button></td></tr>)}</tbody></table></div><div className="flex items-center gap-2 border-t border-[#edf0f4] px-6 py-3 text-[10px] text-[#98a3af]"><Clock3 size={13} /> Decision pipeline last run 8 minutes ago · suppression rules active</div></section>
    </div>
  </AppShell>;
}
