/* Quiet Operations reminder: public copy is direct and specific; asymmetric composition, mineral surfaces, and evidence chips carry the product story. */
import { useState } from "react";
import { Link, useLocation } from "wouter";
import { ArrowUpRight, ChevronDown, Check, ShieldCheck, Sparkles, CircleDot, Menu, X, Zap, BarChart3, MessageCircle, PackageCheck } from "lucide-react";
const onfonNextMark = "/public/manus-storage/onfon-next-mark-red-black_b74af078.png";

const faqs = [
  ["What is Onfon Next?", "Onfon Next is the intelligence and revenue-growth layer around Onfon Mobile. It helps teams understand what a customer needs next and activate that opportunity responsibly."],
  ["How does the Barely-There Rule work?", "Every offer is evaluated against a customer's baseline repayment, tier cap, and combined headroom before it can reach an operator queue."],
  ["Can it suppress a customer automatically?", "Yes. Delinquency, opt-out, unresolved complaints, and contact-frequency fatigue are visible guardrails in the recommendation flow."],
  ["Is this connected to a live checkout?", "This prototype keeps checkout and messaging simulated. It demonstrates the decision flow without sending a real commercial message."],
];

const proofPoints = [
  { icon: BarChart3, title: "See the whole decision", body: "Move from eligibility to channel with every stage visible, explainable, and auditable." },
  { icon: ShieldCheck, title: "Protect customer headroom", body: "Keep daily add-ons inside a cap that feels small, clear, and genuinely affordable." },
  { icon: PackageCheck, title: "Route with confidence", body: "Match product, inventory, dealer, and channel before an offer leaves the station." },
];

function MiniTable() {
  return (
    <div className="overflow-hidden rounded-xl border border-[#dfe5ed] bg-white shadow-[0_20px_60px_rgba(31,50,74,0.12)]">
      <div className="flex items-center justify-between border-b border-[#edf0f4] px-4 py-3"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[#6d6d6d]" /><span className="text-[11px] font-bold text-[#344254]">Recommendation queue</span></div><span className="text-[10px] text-[#8f9aa7]">12 min ago</span></div>
      <div className="grid grid-cols-[1.2fr_0.8fr_0.7fr] border-b border-[#edf0f4] px-4 py-2 text-[9px] font-bold uppercase tracking-[0.12em] text-[#a0a9b5]"><span>Customer</span><span>Headroom</span><span>Signal</span></div>
      {[['Wanjiku N.', 'KES 11/day', 'Ready'], ['Brian O.', 'KES 8/day', 'Review'], ['Mariam A.', 'KES 16/day', 'Ready']].map(([name, headroom, state], i) => <div key={name} className="grid grid-cols-[1.2fr_0.8fr_0.7fr] items-center border-b border-[#f0f2f5] px-4 py-3 text-[10px] last:border-0"><span className="font-semibold text-[#425166]">{name}</span><span className="text-[#6e7d8e]">{headroom}</span><span className={`flex items-center gap-1 font-bold ${state === 'Ready' ? 'text-[#6d6d6d]' : 'text-[#bf765c]'}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{state}</span></div>)}
    </div>
  );
}

export default function Landing() {
  const [, setLocation] = useLocation();
  const [mobileOpen, setMobileOpen] = useState(false);
  const [openFaq, setOpenFaq] = useState(0);
  return (
    <div className="min-h-screen overflow-hidden bg-[#f7f8fb] text-[#202b37]">
      <header className="relative z-30 border-b border-[#edf0f4] bg-[#f7f8fb]/90 backdrop-blur-xl">
        <div className="container flex h-[76px] items-center justify-between">
          <Link href="/" className="flex items-center gap-3"><img src={onfonNextMark} alt="Onfon Next" className="h-11 w-11 object-contain" /><span className="hidden sm:block"><span className="block text-[13px] font-black tracking-[0.16em] text-[#202b37]">ONFON <span className="text-[#e60012]">NEXT</span></span><span className="mt-0.5 block text-[9px] font-bold uppercase tracking-[0.14em] text-[#8c98a6]">The next opportunity layer</span></span></Link>
          <nav className="hidden items-center gap-7 text-[12px] font-semibold text-[#657181] md:flex">
            <a href="#why" className="transition-colors hover:text-[#e60012]">Why Next</a><a href="#workflow" className="transition-colors hover:text-[#e60012]">Workflow</a><a href="#guardrails" className="transition-colors hover:text-[#e60012]">Guardrails</a><a href="#faq" className="transition-colors hover:text-[#e60012]">FAQ</a>
          </nav>
          <div className="hidden items-center gap-3 md:flex"><Link href="/login" className="rounded-lg px-3.5 py-2 text-[12px] font-bold text-[#5d6b7b] transition-colors hover:bg-white hover:text-[#e60012]">Sign in</Link><Link href="/signup" className="qo-button rounded-lg bg-[#e60012] px-4 py-2.5 text-[12px] font-bold text-white shadow-[0_8px_18px_rgba(230,0,18,0.16)] hover:bg-[#b8000e]">Open control station <ArrowUpRight className="ml-1 inline-block" size={14} /></Link></div>
          <button type="button" aria-label="Toggle navigation" onClick={() => setMobileOpen(!mobileOpen)} className="rounded-lg p-2 text-[#657181] md:hidden">{mobileOpen ? <X size={20} /> : <Menu size={20} />}</button>
        </div>
        {mobileOpen && <div className="border-t border-[#edf0f4] bg-white px-5 py-4 md:hidden"><div className="flex flex-col gap-3 text-[13px] font-semibold"><a href="#why" onClick={() => setMobileOpen(false)}>Why Next</a><a href="#workflow" onClick={() => setMobileOpen(false)}>Workflow</a><a href="#guardrails" onClick={() => setMobileOpen(false)}>Guardrails</a><Link href="/login">Sign in</Link><Link href="/signup" className="w-fit rounded-lg bg-[#e60012] px-4 py-2 text-white">Open control station</Link></div></div>}
      </header>

      <main>
        <section className="qo-grain relative border-b border-[#eef1f5] pb-24 pt-16 sm:pb-32 sm:pt-24">
          <div className="container grid items-center gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:gap-8">
            <div className="relative z-10 max-w-[520px] lg:pb-9">
              <div className="qo-fade-up mb-6 flex items-center gap-2 text-[11px] font-bold text-[#6d7785]"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-[#fff0f1] text-[#e60012]"><CircleDot size={13} /></span> Built for the Onfon Mobile growth desk</div>
              <h1 className="qo-display qo-fade-up qo-fade-up-delay-1 max-w-[560px] text-[48px] font-semibold leading-[0.98] text-[#202b37] sm:text-[64px]">Turn every Onfon Mobile relationship into the <span className="text-[#e60012]">next useful thing.</span></h1>
              <p className="qo-fade-up qo-fade-up-delay-2 mt-7 max-w-[470px] text-[16px] leading-[1.65] text-[#657181]">Onfon Next is the intelligence layer around Onfon Mobile — reading repayment context, customer need, inventory, and policy to recommend what comes next at a daily price that respects the customer's room to say yes.</p>
              <div className="qo-fade-up qo-fade-up-delay-3 mt-8 flex flex-wrap items-center gap-3"><button type="button" onClick={() => setLocation('/signup')} className="qo-button rounded-lg bg-[#e60012] px-5 py-3 text-[12px] font-bold text-white shadow-[0_12px_24px_rgba(230,0,18,0.18)] hover:bg-[#b8000e]">Open the control station <ArrowUpRight className="ml-1 inline" size={14} /></button><a href="#workflow" className="flex items-center gap-2 rounded-lg px-3 py-3 text-[12px] font-bold text-[#516174] transition-colors hover:bg-white hover:text-[#e60012]"><span className="flex h-6 w-6 items-center justify-center rounded-full border border-[#cfd8e4] bg-white"><Zap size={11} fill="currentColor" /></span> See the workflow</a></div>
              <div className="mt-11 flex items-center gap-4 text-[11px] text-[#8b96a4]"><div className="flex -space-x-2"><span className="flex h-7 w-7 items-center justify-center rounded-full border-2 border-[#f7f8fb] bg-[#f7d9dc] text-[9px] font-bold text-[#e60012]">AM</span><span className="flex h-7 w-7 items-center justify-center rounded-full border-2 border-[#f7f8fb] bg-[#f8dfd8] text-[9px] font-bold text-[#ad655c]">JO</span><span className="flex h-7 w-7 items-center justify-center rounded-full border-2 border-[#f7f8fb] bg-[#e6ece5] text-[9px] font-bold text-[#5b7f68]">SK</span></div><span>Designed for clear handoffs<br />between people, rules, and inventory.</span></div>
            </div>
            <div className="relative lg:-mr-28">
              <div className="absolute -left-8 top-8 hidden h-48 w-48 rounded-full bg-[#f7d9dc]/70 blur-3xl lg:block" /><div className="absolute -bottom-10 right-8 hidden h-36 w-36 rounded-full bg-[#f6d8d1]/50 blur-3xl lg:block" />
              <div className="relative z-10 rounded-[18px] border border-white/80 bg-white/50 p-3 shadow-[0_30px_90px_rgba(39,55,75,0.12)] backdrop-blur-sm sm:p-5"><img src="/public/manus-storage/onfon-next-hero-dashboard-red-black_940a8691.png" alt="Onfon Next operator dashboard preview" className="w-full rounded-xl" /></div>
              <div className="absolute -bottom-5 -left-3 z-20 hidden rounded-xl border border-[#dce5f0] bg-white px-4 py-3 shadow-[0_15px_30px_rgba(38,55,74,0.12)] sm:block"><div className="qo-eyebrow mb-1">Offer headroom</div><div className="flex items-end gap-2"><span className="text-[22px] font-bold tracking-[-0.05em] text-[#202b37]">KES 11</span><span className="pb-1 text-[10px] font-semibold text-[#6d6d6d]">/ day available</span></div></div>
            </div>
          </div>
        </section>

        <section className="border-b border-[#edf0f4] bg-white py-8"><div className="container flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center"><p className="qo-eyebrow !text-[#a0a9b5]">One station for the next opportunity</p><div className="flex flex-wrap gap-2"><span className="rounded-full border border-[#e4e8ef] px-3 py-1.5 text-[10px] font-bold text-[#657181]">Repayment history</span><span className="rounded-full border border-[#e4e8ef] px-3 py-1.5 text-[10px] font-bold text-[#657181]">Inventory confidence</span><span className="rounded-full border border-[#e4e8ef] px-3 py-1.5 text-[10px] font-bold text-[#657181]">Channel policy</span><span className="rounded-full border border-[#e4e8ef] px-3 py-1.5 text-[10px] font-bold text-[#657181]">Audit trail</span></div></div></section>

        <section id="why" className="container py-24 sm:py-32"><div className="grid gap-12 lg:grid-cols-[0.75fr_1.25fr] lg:gap-20"><div><div className="qo-signal-rail"><p className="qo-eyebrow text-[#e60012]">Why Onfon Next</p><h2 className="qo-display mt-4 max-w-[360px] text-[37px] font-semibold leading-[1.03] text-[#202b37]">From what customers have today to what they need next.</h2></div><p className="mt-6 max-w-[350px] text-[14px] leading-[1.7] text-[#6d7785]">Onfon Mobile knows the relationship customers have today. Next turns seven signals into one clear, operator-ready view of the opportunity that comes after it.</p><a href="#guardrails" className="mt-7 inline-flex items-center gap-2 text-[12px] font-bold text-[#e60012] hover:underline">See the guardrails <ArrowUpRight size={14} /></a></div><div className="grid gap-3 sm:grid-cols-3">{proofPoints.map(({ icon: Icon, title, body }, i) => <div key={title} className={`qo-hover-lift rounded-xl border border-[#e4e8ef] bg-white p-5 ${i === 1 ? 'sm:translate-y-8' : ''}`}><div className="mb-12 flex h-9 w-9 items-center justify-center rounded-lg bg-[#fff0f1] text-[#e60012]"><Icon size={17} strokeWidth={1.8} /></div><h3 className="text-[14px] font-bold tracking-[-0.02em]">{title}</h3><p className="mt-2 text-[12px] leading-[1.6] text-[#778392]">{body}</p></div>)}</div></div></section>

        <section id="workflow" className="border-y border-[#edf0f4] bg-[#fff7f7] py-24 sm:py-28"><div className="container"><div className="mb-12 max-w-[580px]"><p className="qo-eyebrow text-[#e60012]">The operator workflow</p><h2 className="qo-display mt-4 text-[38px] font-semibold leading-[1.02] text-[#202b37]">From Onfon Mobile context to the next useful thing.</h2><p className="mt-5 text-[14px] leading-[1.7] text-[#657181]">Every recommendation carries its own evidence. No black-box score, no hidden cap, no silent suppression.</p></div><div className="grid items-start gap-10 lg:grid-cols-[0.9fr_1.1fr]"><div className="space-y-2">{['Eligibility', 'Affordability', 'Propensity', 'Product match', 'Inventory', 'Economics', 'Channel'].map((item, i) => <div key={item} className={`flex items-center gap-4 border-b border-[#f0d8da] py-3.5 ${i === 1 ? 'text-[#e60012]' : 'text-[#657181]'}`}><span className={`flex h-7 w-7 items-center justify-center rounded-full text-[10px] font-bold ${i === 1 ? 'bg-[#e60012] text-white' : 'bg-white text-[#8c98a6]'}`}>{String(i + 1).padStart(2, '0')}</span><span className="text-[13px] font-bold">{item}</span>{i === 1 && <span className="ml-auto text-[10px] font-bold uppercase tracking-[0.12em]">live signal</span>}</div>)}</div><div className="relative pt-2 lg:pl-10"><div className="absolute left-0 top-0 hidden h-full w-px bg-[#efd0d3] lg:block" /><MiniTable /><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl border border-[#f0d8da] bg-white p-4"><div className="qo-eyebrow mb-2">Combined cap</div><div className="text-[20px] font-bold tracking-[-0.05em]">45%</div><div className="mt-1 text-[10px] text-[#7b8795]">of baseline daily repayment</div></div><div className="rounded-xl border border-[#f0d8da] bg-white p-4"><div className="qo-eyebrow mb-2">Decision latency</div><div className="text-[20px] font-bold tracking-[-0.05em]">&lt; 1 min</div><div className="mt-1 text-[10px] text-[#7b8795]">from rule run to queue</div></div></div></div></div></div></section>

        <section id="guardrails" className="container py-24 sm:py-32"><div className="grid items-center gap-12 lg:grid-cols-[1.1fr_0.9fr]"><div className="qo-frame qo-grain rounded-[20px] p-5 sm:p-8"><div className="flex items-center justify-between border-b border-[#e9edf2] pb-4"><div className="flex items-center gap-2"><ShieldCheck size={16} className="text-[#e60012]" /><span className="text-[12px] font-bold">Governance, in the flow</span></div><span className="rounded-full bg-[#eaf7f1] px-2 py-1 text-[9px] font-bold text-[#6d6d6d]">Enforced</span></div><div className="mt-6 space-y-3">{[['Delinquent customer', 'Offer suppressed', 'coral'], ['Opted-out contact', 'Offer suppressed', 'coral'], ['KES 11/day headroom', 'Offer can proceed', 'blue'], ['Inventory confirmed', 'Route to dealer', 'blue']].map(([a,b,c]) => <div key={a} className="flex items-center justify-between rounded-lg border border-[#edf0f4] bg-white px-4 py-3"><div><div className="text-[11px] font-bold text-[#445266]">{a}</div><div className="mt-1 text-[10px] text-[#8994a2]">Policy signal</div></div><span className={`rounded-full px-2 py-1 text-[9px] font-bold ${c === 'coral' ? 'bg-[#fff0ed] text-[#bd6b60]' : 'bg-[#fff0f1] text-[#e60012]'}`}>{b}</span></div>)}</div></div><div className="max-w-[440px]"><p className="qo-eyebrow text-[#bd6b60]">Responsible by default</p><h2 className="qo-display mt-4 text-[38px] font-semibold leading-[1.04]">Make the safe decision the easy decision.</h2><p className="mt-5 text-[14px] leading-[1.75] text-[#6d7785]">Suppression is not a footnote. The station makes customer protection visible at the exact moment an operator is about to act.</p><div className="mt-7 space-y-3 text-[12px] font-semibold text-[#536174]"><div className="flex items-center gap-2"><Check size={15} className="text-[#6d6d6d]" /> Barely-There Rule in every offer</div><div className="flex items-center gap-2"><Check size={15} className="text-[#6d6d6d]" /> Contact-frequency caps surfaced early</div><div className="flex items-center gap-2"><Check size={15} className="text-[#6d6d6d]" /> Every recommendation has a plain-language why</div></div></div></div></section>

        <section id="faq" className="border-t border-[#edf0f4] bg-white py-24 sm:py-28"><div className="container grid gap-12 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="qo-eyebrow text-[#e60012]">Questions, answered</p><h2 className="qo-display mt-4 max-w-[330px] text-[38px] font-semibold leading-[1.04]">A clearer system makes for better conversations.</h2><p className="mt-5 max-w-[320px] text-[14px] leading-[1.7] text-[#6d7785]">A clearer operating layer for turning today’s customer relationship into tomorrow’s useful conversation.</p></div><div className="border-t border-[#dfe5ed]">{faqs.map(([q,a], i) => <div key={q} className="border-b border-[#dfe5ed]"><button type="button" onClick={() => setOpenFaq(openFaq === i ? -1 : i)} className="flex w-full items-center justify-between gap-4 py-5 text-left text-[13px] font-bold text-[#344254]"><span>{q}</span><ChevronDown size={16} className={`shrink-0 text-[#8d98a6] transition-transform duration-200 ${openFaq === i ? 'rotate-180 text-[#e60012]' : ''}`} /></button>{openFaq === i && <p className="max-w-[620px] pb-5 text-[12px] leading-[1.7] text-[#748091]">{a}</p>}</div>)}</div></div></section>

        <section className="bg-[#e60012] py-16 text-white sm:py-20"><div className="container grid items-end gap-8 lg:grid-cols-[1fr_auto]"><div><p className="qo-eyebrow !text-white/60">Your next shift, made legible</p><h2 className="qo-display mt-4 max-w-[620px] text-[42px] font-semibold leading-[1] sm:text-[54px]">Operate with more context. Offer with more care.</h2></div><div><button type="button" onClick={() => setLocation('/signup')} className="qo-button rounded-lg bg-white px-5 py-3 text-[12px] font-bold text-[#e60012] shadow-[0_12px_26px_rgba(5,40,110,0.25)] hover:bg-[#fff7f7]">Enter Onfon Next <ArrowUpRight className="ml-1 inline" size={14} /></button><p className="mt-3 text-[10px] text-white/60">UI-only prototype · no messages are sent</p></div></div></section>
      </main>

      <footer className="bg-[#202b37] py-10 text-white"><div className="container flex flex-col justify-between gap-8 sm:flex-row sm:items-end"><div><div className="flex items-center gap-3"><img src={onfonNextMark} alt="Onfon Next" className="h-12 w-12 object-contain" /><div><div className="text-[13px] font-black tracking-[0.16em]">ONFON <span className="text-[#7fb0ff]">NEXT</span></div><div className="mt-0.5 text-[9px] font-bold uppercase tracking-[0.14em] text-white/45">From Onfon Mobile</div></div></div><p className="mt-4 max-w-[280px] text-[11px] leading-[1.6] text-white/45">The intelligence and revenue-growth layer for the customers Onfon Mobile already serves.</p></div><div className="flex flex-wrap gap-x-7 gap-y-3 text-[11px] font-semibold text-white/55"><a href="#why" className="hover:text-white">Why Next</a><a href="#workflow" className="hover:text-white">Workflow</a><a href="#guardrails" className="hover:text-white">Guardrails</a><Link href="/login" className="hover:text-white">Sign in</Link></div><div className="text-[10px] text-white/35">© 2026 Onfon Next · Prototype</div></div></footer>
    </div>
  );
}
